name: Automated Data Preprocessing Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    # cek repository kode 
    - name: Checkout Code
      uses: actions/checkout@v3

    # setup env
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # install depedensi
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # run script
    - name: Generate Raw Data Simulation
      run: python generate_raw_data.py

    # automation
    - name: Run Data Preprocessing Automation
      run: python automate_Nama-siswa.py

    # verifed
    - name: Verify Processed Artifact
      run: |
        if [ -f "namadataset_preprocessing/credit_data_processed.csv" ]; then
          echo "Artifact Preprocessing Berhasil Terbentuk!"
          head -n 5 namadataset_preprocessing/credit_data_processed.csv
        else
          echo "Error: Artifact tidak ditemukan!"
          exit 1
        fi
